"""add index of user_id in table user

Revision ID: 4573acea8246
Revises: 53b9ae3402c7
Create Date: 2018-07-25 15:44:28.134787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4573acea8246'
down_revision = '53b9ae3402c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_project_id', table_name='project')
    op.drop_table('project')
    op.create_index('ix_user_user_id', 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_user_id', table_name='user')
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_project_project_id', 'project', ['project_id'], unique=False)
    # ### end Alembic commands ###
