"""add index of user_id in table user

Revision ID: 7fa4861c26fa
Revises: 4573acea8246
Create Date: 2018-07-25 17:07:48.957443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa4861c26fa'
down_revision = '4573acea8246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
